"""Publish whitespace-clean Git docs without changing the frozen D5 artifact."""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import xml.etree.ElementTree as ET

from defense_mvp.reporting.core import json_bytes, sha256_file
from defense_mvp.reporting.publication import public_files


def svg_semantics(data: bytes):
    def node(element):
        attrs = dict(element.attrib)
        if element.tag.endswith('}path') and 'd' in attrs:
            attrs['d'] = ' '.join(attrs['d'].split())
        def text(value):
            return value if value and value.strip() else None
        return (element.tag, sorted(attrs.items()), text(element.text),
                text(element.tail), [node(child) for child in element])
    return node(ET.fromstring(data))


def normalize_svg(data: bytes) -> bytes:
    result = ('\n'.join(line.rstrip(' \t') for line in
                        data.decode('utf-8').splitlines()) + '\n').encode('utf-8')
    if svg_semantics(result) != svg_semantics(data):
        raise ValueError('SVG whitespace edit changes XML semantics')
    return result


def expected_files(root: Path, repository: Path):
    files = public_files(root, repository)
    receipt = json.loads(files.pop('d5_generated/public-export.json'))
    changes = {}
    for name, original in list(files.items()):
        if name.endswith('.svg'):
            files[name] = normalize_svg(original)
            changes[name] = {'source_sha256': hashlib.sha256(original).hexdigest(),
                             'method': 'rstrip horizontal line-end whitespace; XML semantics checked'}
    receipt.update(schema_version='2', relationship=(
        'report changes relative links only; SVG line-end whitespace normalized with '
        'XML semantics equality; script, plan, CSV and PNG are byte copies'),
        transformations=changes, publisher={
            'path': 'scripts/defense_mvp/publish_d5_docs.py',
            'sha256': sha256_file(Path(__file__))},
        files={name: hashlib.sha256(data).hexdigest() for name, data in files.items()})
    files['d5_generated/public-export.json'] = json_bytes(receipt)
    return files


def verify(root: Path, repository: Path, destination: Path):
    files = expected_files(root, repository)
    for name, data in files.items():
        if (destination / name).read_bytes() != data:
            raise ValueError('published document drift: ' + name)
    generated = {p.relative_to(destination).as_posix()
                 for p in (destination / 'd5_generated').rglob('*') if p.is_file()}
    if generated != {name for name in files if name.startswith('d5_generated/')}:
        raise ValueError('unknown/missing generated publication file')
    return {'status': 'passed', 'public_files': len(files),
            'svg_semantics_checked': sum(name.endswith('.svg') for name in files)}


def publish(root: Path, repository: Path, destination: Path):
    expected = expected_files(root, repository)
    raw = public_files(root, repository)
    # Preflight every existing file before writing any file. Only known raw/final
    # generated bytes may be replaced; user edits hard-fail without partial writes.
    for name, data in expected.items():
        p = destination / name
        if p.exists() and p.read_bytes() not in (raw[name], data):
            raise ValueError('refusing to overwrite an edited document: ' + name)
    for name, data in expected.items():
        p = destination / name
        if not p.exists() or p.read_bytes() != data:
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_bytes(data)
    return verify(root, repository, destination)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--root', type=Path, required=True)
    parser.add_argument('--repository', type=Path, default=Path.cwd())
    parser.add_argument('--destination', type=Path, required=True)
    parser.add_argument('--verify', action='store_true')
    args = parser.parse_args()
    result = (verify if args.verify else publish)(args.root, args.repository, args.destination)
    print(json.dumps(result, sort_keys=True))
